#/* while true ; pw-cli ls Node | grep -i nemo -B10 -A20 ; end */
stream.rules = [
	{
	  matches = [
		  {
				application.name = "~ALSA.*nemo.*"
		  }
	  ],
	  actions = {
		update-props = {
		 state.restore-props = false
		 state.restore-target = false
		 state.default-volume = 0.2
		}
	  }
	}
]
