#scalefullscreen=0.75
#scaleforcedwindow=2.0  # default
tooltipborder=1

#minmousemove=2
#deadzonesize=0.55
minmousemove=3
deadzonesize=0

font=monospace
scalefullscreen=1.2
seekbarfg=933CE3
windowcontrols=no

timetotal=no
showtitle=yes
showtitleonpause=no
