 Section "InputClass"
     Identifier   "NuleaTrackball"
     MatchDevicePath "/dev/input/event*"
     MatchProduct "CHERRY"
     Driver       "libinput"
     #Option       "ButtonMapping"      "1 2 3 4 5 6 7 13 12 10"
     #Option       "ButtonMapping"      "1 2 3 4 5 6 7 2 13 10"
     Option       "ButtonMapping"      "1 12 3 4 5 6 7 2 13 10"
     # $ xmodmap -e 'pointer = 1 12 3 4 5 6 7 2 13 10'
     # $ xmodmap -pp
 EndSection
